name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: build (${{ matrix.os }}-amd64)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux, windows, darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.os }}" = "windows" ]; then EXT=".exe"; fi
          BIN_NAME="argocd-game-tools_${{ github.ref_name }}_${{ matrix.os }}_amd64${EXT}"
          GOOS=${{ matrix.os }} GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o "dist/${BIN_NAME}" .
          ls -l dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: dist/*

  release:
    name: publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-linux
          path: dist

      - name: Download windows artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-windows
          path: dist

      - name: Download darwin artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-darwin
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false

